version: 2.1

jobs:
  test:
    docker:
      # Primary container: JDK‑17 with Gradle pre‑installed
      - image: cimg/openjdk:17.0

      # Secondary service container: rqlite node
      - image: rqlite/rqlite:8.42.0
        name: rqlite
        ports:
          - 4001:4001

    environment:
      RQLITE_URL: http://rqlite:4001              # picked up by integration tests

    steps:
      - checkout

      # Gradle dependency cache
      - restore_cache:
          keys:
            - gradle-{{ checksum "gradle.lockfile" }}
            - gradle-

      # Wait for the rqlite service container to become healthy
      - run:
          name: Wait for rqlite
          command: |
            for i in {1..30}; do
              if curl -sf http://rqlite:4001/healthz >/dev/null; then
                echo "rqlite is up"
                exit 0
              fi
              sleep 1
            done
            echo "rqlite failed to start" >&2
            exit 1

      # Build, test, and generate coverage report
      - run:
          name: Build & test
          command: ./gradlew --no-daemon clean build jacocoTestReport

      # Cache updated Gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "gradle.lockfile" }}

      # Persist JUnit test results
      - store_test_results:
          path: build/test-results/test

      # Persist HTML coverage report
      - store_artifacts:
          path: build/reports/jacoco/test/html
          destination: coverage-report

workflows:
  sanity:
    jobs:
      - test
