name: PR Tests
on: { pull_request: { branches: [ master ] } }
jobs:
  test:
    runs-on: ubuntu-latest
    container: docker.io/library/gradle:8-jdk21
    services: { rqlite: { image: rqlite/rqlite:8.42.0, ports: [ 4001:4001 ] } }
    env: { RQLITE_URL: http://rqlite:4001 }
    steps:
      - uses: actions/checkout@v4
      - name: Wait for rqlite
        run: |
          end=$((SECONDS+120))
          until curl -sf http://rqlite:4001/healthz; do
            if [ $SECONDS -ge $end ]; then
              echo "rqlite failed to start" >&2
              curl -v http://rqlite:4001/healthz || true
              exit 1
            fi
            sleep 2
          done
          echo "rqlite is up"
      - name: Build & test
        run: gradle clean build jacocoTestReport
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with: { name: test-results, path: build/test-results/test }
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with: { name: coverage-report, path: build/reports/jacoco/test/html }
